apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crypto-live-detection
resources:
  - ../../base

images:
  - name: YOUR_REGISTRY/api-service
    newTag: "1.0.0"
  - name: YOUR_REGISTRY/ingestor-service
    newTag: "1.0.0"
  - name: YOUR_REGISTRY/detector-service
    newTag: "1.0.0"
  - name: YOUR_REGISTRY/web-frontend
    newTag: "1.0.0"

patches:
  - target:
      kind: Deployment
      name: api-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: web-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
