apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crypto-live-detection
resources:
  - ../../base

images:
  - name: YOUR_REGISTRY/api-service
    newTag: dev
  - name: YOUR_REGISTRY/ingestor-service
    newTag: dev
  - name: YOUR_REGISTRY/detector-service
    newTag: dev
  - name: YOUR_REGISTRY/web-frontend
    newTag: dev
