apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-live-detection-prod
spec:
  project: default
  source:
    repoURL: https://YOUR_GIT_REPO_URL.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: crypto-live-detection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
