apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis.yaml
  - api-service.yaml
  - ingestor-service.yaml
  - detector-service.yaml
  - web-frontend.yaml
  - ingress.yaml
