name: Full Stack CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  # 1. API SERVİSİ İÇİN BUILD
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login2Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build&PushAPI
        uses: docker/build-push-action@v4
        with:
          context: ./btc-feed/services/api-service 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/btc-api:v${{ github.run_number }}

  # 2. WORKER SERVİSİ İÇİN BUILD
  build-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login2Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build&PushWorker
        uses: docker/build-push-action@v4
        with:
          context: ./btc-feed/services/worker-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/btc-worker:v${{ github.run_number }}

  # 3. FRONTEND SERVİSİ İÇİN BUILD
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login2Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build&PushFrontend
        uses: docker/build-push-action@v4
        with:
          context: ./btc-feed/services/frontend-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/btc-frontend:v${{ github.run_number }}
