name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:       #Manuel tetikleme butonu

jobs:
  # --- API BUILD ---
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ve Push (API)
        uses: docker/build-push-action@v4
        with:
          context: ./btc-feed/services/api-service 
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/btc-api:v${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/btc-api:latest

  # --- FRONTEND BUILD ---
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ve Push (Frontend)
        uses: docker/build-push-action@v4
        with:
          context: ./btc-feed/services/frontend-service
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/btc-frontend:v${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/btc-frontend:latest

  # --- WORKER BUILD ---
  build-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ve Push (Worker)
        uses: docker/build-push-action@v4
        with:
          context: ./btc-feed/services/worker-service
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/btc-worker:v${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/btc-worker:latest